/**
 * BASE DE DATOS DE RESTAURANTES - JAPÓN 2026
 * Organizado por ciudades y áreas para integración contextual.
 */

const restaurantData = [
    {
        id: "my-neighbor",
        name: "MY NEIGHBOR",
        category: "Café & Brunch",
        description: "Un café moderno y acogedor, famoso por sus desayunos, repostería casera y café de especialidad. Ideal para empezar el día.",
        area: "Nishi Ward, Osaka",
        city: "OSAKA",
        address: "Grand-K, 1-chōme-13-33 Nishihonmachi, Nishi Ward, Osaka, 550-0005, Japón",
        google_maps_place_id: "ChIJYeGbSVXnAGARqeazBcJQF3I",
        rating: 4.7,
        specialty: "Tarta de Queso & Café de Especialidad",
        image: "images/restaurantes/my-neighbor.jpg",
        nearTo: ["Castillo de Osaka", "Museo de Historia de Osaka", "Parque del Castillo", "Nakanoshima", "Honmachi", "Umeda"] // Áreas cercanas para recomendación
    },
    {
        id: "yakiniku-kitan-minamisenba",
        name: "Yakiniku KITAN Minamisenba",
        category: "Yakiniku (Barbacoa Japonesa)",
        description: "Un restaurante de Yakiniku elegante y muy bien valorado, conocido por su carne Wagyu de excelente calidad y su ambiente sofisticado.",
        area: "Minamisenba, Osaka",
        city: "OSAKA",
        address: "4-chōme-11-22 B1FYOC Minamisenba, Chuo Ward, Osaka, 542-0081, Japón",
        google_maps_place_id: "ChIJoRGXxY7nAGARAdFPBOBTQ78",
        rating: 4,
        specialty: "Cortes Seleccionados de Wagyu A5",
        image: "images/restaurantes/yakiniku-kitan-minamisenba.jpg",
        nearTo: ["Shinsaibashi", "Shinsaibashi Parco", "Minamisenba", "Amerikamura", "Shinsaibashi-suji", "Umeda Sky Building"]
    },
    {
        id: "nikugoro-amerikamura",
        name: "Nikugoro Amerikamura (肉五郎)",
        category: "Yakiniku (Barbacoa Japonesa)",
        description: "Especializado en barbacoa japonesa. Es un lugar animado y popular entre los locales, situado en el corazón del barrio joven de la ciudad.",
        area: "Amerikamura, Osaka",
        city: "OSAKA",
        address: "2-chōme-3-16 Nishishinsaibashi, Chuo Ward, Osaka, 542-0086, Japón",
        google_maps_place_id: "ChIJL8JR_4znAGAR7tEWPJpWtR0",
        rating: 4.9,
        specialty: "Yakiniku (Barbacoa de Ternera)",
        image: "images/restaurantes/nikugoro-amerikamura.jpg",
        nearTo: ["Amerikamura", "Shinsaibashi", "Shinsaibashi Parco", "Shinsaibashi-suji", "Dotonbori", "Calle Ebisubashisuji"]
    },
    {
        id: "kitan-hibiki-yakiniku",
        name: "KITAN HIBIKI YAKINIKU & STEAK (㐂舌 響)",
        category: "Yakiniku & Steak Premium",
        description: "Ofrece cortes premium de carne y una experiencia de cena de alta calidad, enfocada en el sabor auténtico del buey japonés (Wagyu).",
        area: "Namba, Osaka",
        city: "OSAKA",
        address: "1-chōme-1-7 Namba, Chuo Ward, Osaka, 542-0076, Japón",
        google_maps_place_id: "ChIJtZqLbwDnAGARfxhkdtkKOX0",
        rating: 4.3,
        specialty: "Chuletón de Wagyu Madurado",
        image: "images/restaurantes/kitan-hibiki-yakiniku.jpg",
        nearTo: ["Santuario Namba Yasaka", "Calle Ebisubashisuji", "Dotonbori", "Namba", "Hozenji Yokocho", "Nipponbashi", "Den Den Town", "Cena en Dotonbori"]
    },
    {
        id: "matsusakagyu-yakiniku-m-namba",
        name: "Matsusakagyu Yakiniku M (Namba Branch)",
        category: "Yakiniku (Carne de Matsusaka)",
        description: "Famoso por servir la exclusiva carne de Matsusaka (una de las tres mejores de Japón). Es una parada obligatoria para los amantes de la carne.",
        area: "Namba, Osaka",
        city: "OSAKA",
        address: "3-11 Nanbasennichimae, Chuo Ward, Osaka, 542-0075, Japón",
        google_maps_place_id: "ChIJa0f0lRTnAGARXNWOLs7nBqg",
        rating: 4.8,
        specialty: "Carne de Matsusaka a la Parrilla",
        image: "images/restaurantes/matsusakagyu-yakiniku-m-namba.jpg",
        nearTo: ["Santuario Namba Yasaka", "Dotonbori", "Namba", "Ebisubashisuji", "Calle Ebisubashisuji", "Hozenji Yokocho", "Cena en Dotonbori"]
    },
    {
        id: "yakiniku-m-hozenji",
        name: "Yakiniku M Hozenji Yokocho",
        category: "Yakiniku (Carne de Matsusaka)",
        description: "Sucursal de la prestigiosa cadena 'M', ubicada en un callejón histórico con mucho encanto (Hozenji Yokocho), ofreciendo una atmósfera más tradicional.",
        area: "Hozenji Yokocho (Namba), Osaka",
        city: "OSAKA",
        address: "1-chōme-1-19 Namba, Chuo Ward, Osaka, 542-0076, Japón",
        google_maps_place_id: "ChIJa0f0lRTnAGARXNWOLs7nBqg",
        rating: 4.8,
        specialty: "Menú Degustación de Buey Matsusaka",
        image: "images/restaurantes/yakiniku-m-hozenji.jpg",
        nearTo: ["Hozenji Yokocho", "Calle Ebisubashisuji", "Dotonbori", "Namba", "Ebisubashisuji", "Cena en Dotonbori"]
    },
        {
        id: "bek-shinsaibashi",
        name: "Blue Entrance Kitchen (BEK Shinsaibashi)",
        category: "Tacos Gourmet & Café",
        description: "Moderno local de tacos fusión gourmet y deliciosa repostería en un ambiente muy chic y relajado en Shinsaibashi.",
        area: "Amerikamura, Osaka",
        city: "OSAKA",
        address: "Japón, 〒542-0086 Osaka, Chuo Ward, Nishishinsaibashi, 2 Chome−6−7 Dotonbori Building 4F S-FRONT",
        google_maps_place_id: "ChIJB8K6WgDnAGARajakw3NSzKc",
        rating: 4.4,
        specialty: "Tacos de Ternera Fusión & Café",
        image: "images/restaurantes/bek-shinsaibashi.jpg",
        nearTo: ["Amerikamura", "Shinsaibashi", "Shinsaibashi Parco", "Dotonbori", "Shinsaibashi-suji"]
    },
    {
        id: "kobe-beef-miyabi-kitanosaka",
        name: "Kobe Beef MIYABI Kitanosaka Store",
        category: "Carne de Kobe (Teppanyaki)",
        description: "Restaurante que sirve auténtica y certificada carne de Kobe cocinada al estilo teppanyaki sobre plancha caliente frente a ti. Una experiencia gourmet indispensable para tu excursión a Kobe.",
        area: "Kitanosaka, Kobe (Excursión desde Osaka)",
        city: "OSAKA",
        address: "Japón, 〒650-0001 Hyogo, Kobe, Chuo Ward, Kanocho, 4 Chome-8-19",
        google_maps_place_id: "ChIJyW7UIRXnAGARnnWtyiPd6Io",
        rating: 4.8,
        specialty: "Kobe Beef en Plancha Teppanyaki",
        image: "images/restaurantes/kobe-beef-miyabi-kitanosaka.jpg",
        nearTo: ["Kobe", "Sannomiya", "Kitanosaka", "Puerto de Kobe", "Harborland", "Excursión a Kobe"]
    },
    {
        id: "moeyo-mensuke-fukushima",
        name: "Moeyo Mensuke (燃えよ麺助)",
        category: "Ramen de Pato (Kamo Ramen)",
        description: "Uno de los templos de ramen más aclamados de Osaka. Famoso por su caldo de pato premium de Wakayama (Kamo Soba) con una profundidad de sabor espectacular.",
        area: "Fukushima, Osaka",
        city: "OSAKA",
        address: "5 Chome-12-21 Fukushima, Fukushima Ward, Osaka, 553-0003, Japón",
        google_maps_place_id: "ChIJaXqjjj3nAGARxZjXwNa2GdM",
        rating: 4.4,
        specialty: "Kamo Soba (Ramen de Pato Premium)",
        image: "images/restaurantes/moeyo-mensuke-fukushima.jpg",
        nearTo: ["Umeda Sky Building", "Nakanoshima", "Umeda", "Fukushima", "Estación de Osaka", "Almuerzo en Umeda", "Cruceros por el río Okawa"]
    },
    {
        id: "acai-bowl-blab-shinsaibashi",
        name: "Shinsaibashi Acai Bowl B-lab",
        category: "Café & Acai Bowls",
        description: "El lugar ideal en Shinsaibashi para disfrutar de acai bowls frescos, saludables y muy vistosos decorados con frutas y superalimentos.",
        area: "Higashi Shinsaibashi, Osaka",
        city: "OSAKA",
        address: "Japón, 〒542-0083 Osaka, Chuo Ward, Higashishinsaibashi, 2 Chome−8−7 日宝Nストリートビル １階",
        google_maps_place_id: "ChIJ21aVzCfnAGARRGAiM7jwAaI",
        rating: 4.6,
        specialty: "Acai Bowl con Frutas Frescas",
        image: "images/restaurantes/acai-bowl-blab-shinsaibashi.jpg",
        nearTo: ["Shinsaibashi Parco", "Dotonbori", "Shinsaibashi", "Higashi Shinsaibashi", "Shinsaibashi-suji"]
    },
    {
        id: "tenma-sakaba-sushikin",
        name: "Tenma Sakaba Sushi-Kin",
        category: "Sushi & Sakaba (Taberna)",
        description: "Una animada taberna en Tenma que ofrece sushi fresquísimo a precios populares, combinando un ambiente local tradicional y grandes tragos de sake.",
        area: "Tenma, Osaka",
        city: "OSAKA",
        address: "5 Chome-7-28 Tenjinbashi, Kita Ward, Osaka, 530-0041, Japón",
        google_maps_place_id: "ChIJs6an-xLnAGARRNX6JZo5dOg",
        rating: 4.2,
        specialty: "Nigiris de Salmón y Atún Rojo",
        image: "images/restaurantes/tenma-sakaba-sushikin.jpg",
        nearTo: ["Tenma", "Calle Comercial Tenjinbashisuji", "Tenjinbashisuji", "Museo de la Vivienda y la Vida de Osaka", "Umeda Sky Building", "Umeda"]
    },
    {
        id: "shinsaibashi-maruhana",
        name: "Japanese Buffet Dining Shinsaibashi Maruhana",
        category: "Buffet Libre (Marisco & Wagyu)",
        description: "Un espectacular buffet libre especializado en cangrejo gigante, carne Wagyu y platos tradicionales japoneses en un ambiente ideal para grupos y familias.",
        area: "Shinsaibashi, Osaka",
        city: "OSAKA",
        address: "FUKU BLD. Shinsaibashi 2F A, 2-8-26 Higashi-Shinsaibashi, Chuo-ku, Osaka, 542-0083, Japón",
        google_maps_place_id: "ChIJ15r8S7HnAGARhqMnLb8yGzs",
        rating: 4.5,
        specialty: "Buffet Libre de Cangrejo & Wagyu A5",
        image: "images/restaurantes/shinsaibashi-maruhana.jpg",
        nearTo: ["Shinsaibashi Parco", "Dotonbori", "Shinsaibashi", "Higashi Shinsaibashi", "Shinsaibashi-suji"]
    },
    {
        id: "unagi-nakasho-namba",
        name: "Unagi Nakasho Namba (장어 de Nakasho)",
        category: "Anguila (Unagi)",
        description: "Especialistas en platos de anguila tradicional (Unadon y Hitsumabushi) asada al carbón de forma impecable, con una textura crujiente por fuera y tierna por dentro.",
        area: "Namba, Osaka",
        city: "OSAKA",
        address: "Japón, 〒542-0076 Osaka, Chuo Ward, Namba, 1 Chome−4−10 h+ Building 4F",
        google_maps_place_id: "ChIJBYq2q7rnAGARAbKreEiLQ4g",
        rating: 4.8,
        specialty: "Hitsumabushi (Anguila Tradicional)",
        image: "images/restaurantes/unagi-nakasho-namba.jpg",
        nearTo: ["Dotonbori", "Namba Parks", "Namba", "Ebisubashisuji", "Den Den Town", "Doguyasuji"]
    },
    {
        id: "kobe-beef-amami",
        name: "Kobe Beef Amami (神戸牛 天海)",
        category: "Carne de Kobe (Teppanyaki)",
        description: "Especializado en exquisitos platos de carne de Kobe de primera calidad cocinados al momento en parrilla caliente teppanyaki frente a los comensales.",
        area: "Sannomiya, Kobe (Excursión desde Osaka)",
        city: "OSAKA",
        address: "Japón, 〒650-0012 Hyogo, Kobe, Chuo Ward, Kitanagasadori, 1 Chome−8−1",
        google_maps_place_id: "ChIJ658auBmPAGARWewJxUaWZPM",
        rating: 4.9,
        specialty: "Solomillo de Kobe a la Plancha",
        image: "images/restaurantes/kobe-beef-amami.jpg",
        nearTo: ["Kobe", "Sannomiya", "Puerto de Kobe", "Harborland", "Excursión a Kobe"]
    },
    {
        id: "wagyu-idaten-namba",
        name: "Wagyu IDATEN (匠のお重 和牛 韋駄天)",
        category: "Cajas de Wagyu (Wagyu Ju)",
        description: "Exquisito restaurante especializado en servir carne Wagyu de gran calidad fileteada dentro de las tradicionales cajas de laca japonesas (Oju).",
        area: "Namba, Osaka",
        city: "OSAKA",
        address: "Japón, 〒542-0076 Osaka, Chuo Ward, Namba, 1 Chome−8−20 嘉光ビル 2階",
        google_maps_place_id: "ChIJF9AXoBznAGARi-T-JyJ_UEQ",
        rating: 4.7,
        specialty: "Wagyu Oju (Caja de Ternera en Laca)",
        image: "images/restaurantes/wagyu-idaten-namba.jpg",
        nearTo: ["Dotonbori", "Santuario Namba Yasaka", "Calle Ebisubashisuji", "Namba", "Ebisubashisuji", "Cena en Dotonbori"]
    },
    // --- RESTAURANTES DE KIOTO ---
    {
        id: "gyukatsu-motomura-kyoto",
        name: "Gyukatsu Motomura (Kyoto Sanjo)",
        category: "Gyukatsu (Ternera empanada)",
        description: "Famoso por su ternera empanada (Gyukatsu) servida poco hecha, que puedes terminar a la plancha en tu propia piedra caliente. ¡Obligatorio probarlo!",
        area: "Sanjo Kawaramachi, Kioto",
        city: "KYOTO",
        address: "Sanjo-dori, Nakagyo Ward, Kyoto",
        google_maps_place_id: "ChIJWepYqWIJAWARNvWmXIq6Me8",
        rating: 4.9,
        specialty: "Gyukatsu (Ternera Empanada a la Piedra)", 
        image: "images/restaurantes/gyukatsu-motomura-kyoto.jpg",
        nearTo: ["Calle Comercial Kawaramachi", "Paseo por el río Kamo", "Pontocho", "Kawaramachi", "Sanjo", "Teramachi", "Mercado Nishiki", "Paseo Nocturno Pontocho", "Museo de Samuráis y Ninjas de Kioto"]
    },
    {
        id: "chao-chao-gyoza-kiyamachi",
        name: "Chao Chao Gyoza (Sanjo Kiyamachi)",
        category: "Gyozas & Taberna",
        description: "Uno de los locales de gyozas más divertidos y populares de Kioto. Auténtico ambiente de izakaya local con unas empanadillas excepcionales increíbles de probar a un súper precio.",
        area: "Sanjo Kiyamachi, Kioto",
        city: "KYOTO",
        address: "117 Ishiyacho, Nakagyo Ward, Kyoto",
        google_maps_place_id: "ChIJp_hFTpMIAWARV2uDmrqPBCo",
        rating: 4.6,
        specialty: "Gyoza de Cerdo y Ajo Chao Chao",
        image: "images/restaurantes/chao-chao-gyoza-kiyamachi.jpg",
        nearTo: ["Calle Comercial Kawaramachi", "Pontocho", "Gion", "Kiyamachi", "Sanjo", "Gion Shirakawa", "Mercado Nishiki", "Museo de Samuráis y Ninjas de Kioto"]
    },
    {
        id: "tempura-no-mise-gen",
        name: "Tempura no Mise Gen",
        category: "Tempura Especializada",
        description: "Un íntimo local especializado en tempura tradicional de Kioto. Podréis sentaros en la barra a comer unos espectaculares tendon (cuencos de arroz recubiertos de tempura recién frita).",
        area: "Sanjo, Kioto",
        city: "KYOTO",
        address: "Nakagyo Ward, Kyoto",
        google_maps_place_id: "ChIJWZmsaiIJAWARUUpbnF_If0E",
        rating: 4.9,
        specialty: "Tendon (Bol de Tempura Crujiente)",
        image: "images/restaurantes/tempura-no-mise-gen.jpg",
        nearTo: ["Calle Comercial Kawaramachi", "Paseo por el río Kamo", "Sanjo", "Kiyamachi", "Teramachi", "Mercado Nishiki"]
    },
    {
        id: "unagi-sumito",
        name: "Unagi Sumito",
        category: "Anguila (Unagi / Hitsumabushi)",
        description: "Especialistas en anguila de agua dulce de primera calidad asada al carbón. Su hitsumabushi (estilo de Nagoya) se come en varias fases con té y condimentos.",
        area: "Higashiyama, Kioto",
        city: "KYOTO",
        address: "Nichome 51 B1F, Higashiyama Ward, Kyoto",
        google_maps_place_id: "ChIJexZ39kMJAWARdbDD30BFfdo",
        rating: 5,
        specialty: "Unajyu (Anguila sobre Arroz en Caja)",
        image: "images/restaurantes/unagi-sumito.jpg",
        nearTo: ["Higashiyama", "Kiyomizu-dera", "Santuario Yasaka", "Gion", "Ninenzaka", "Sannenzaka", "Gion Shirakawa", "Templo Kennin-ji", "Fushimi Inari"]
    },
        {
        id: "kyoto-engine-ramen",
        name: "KYOTO ENGINE RAMEN",
        category: "Ramen Especializado",
        description: "Un local de ramen moderno y popular conocido por sus sabrosos caldos caseros y deliciosas opciones vegetarianas y libres de gluten.",
        area: "Narayacho, Kyoto",
        city: "KYOTO",
        address: "580-2 Nakanocho, Nakagyo Ward, Kyoto, 604-8042, Japón",
        google_maps_place_id: "ChIJWwNkMLoJAWAR7chswFIMOEI",
        rating: 4.5,
        specialty: "Ramen Engine (Caldo Denso y Sabroso)",
        image: "images/restaurantes/kyoto-engine-ramen.jpg",
        nearTo: ["Calle Comercial Kawaramachi", "Pontocho", "Gion", "Mercado Nishiki", "Nishiki", "Teramachi", "Gion Shirakawa", "Castillo de Nijo", "Palacio Imperial de Kioto", "Torre de Kioto"]
    },
    {
        id: "kyoto-kani-gin",
        name: "Kyoto KANI-GIN Kawaramachi Store",
        category: "Cangrejo & Marisco",
        description: "Especialistas en cangrejo de las nieves y cangrejo real cocinado en diversas formas: tempura, sushi, sashimi y a la parrilla, con increíbles vistas.",
        area: "Narayacho, Kyoto",
        city: "KYOTO",
        address: "Japón, 〒604-8033 Kyoto, Nakagyo Ward, Narayacho, 291 DECK by COAST 5F",
        google_maps_place_id: "ChIJq4SHKJoJAWARwAX-XABwbSM",
        rating: 4.5,
        specialty: "Tempura y Sashimi de Cangrejo Nevado",
        image: "images/restaurantes/kyoto-kani-gin.jpg",
        nearTo: ["Calle Comercial Kawaramachi", "Pontocho", "Gion", "Sanjo", "Mercado Nishiki", "Nishiki", "Gion Shirakawa"]
    },
        {
        id: "sabo-kinkakuan-kyoto",
        name: "Sabo Kinkaku-an (茶房 金閣庵)",
        category: "Casa de Té & Dulces Tradicionales",
        description: "Encantadora casa de té tradicional japonesa y repostería artesanal ubicada a pocos pasos del templo Kinkaku-ji. Un rincón mágico para disfrutar de té matcha de Uji y dulces japoneses frente a un idílico jardín zen.",
        area: "Kinkaku-ji, Kioto",
        city: "KYOTO",
        address: "36-1 Kinugasanishi Goshonouchicho, Kita Ward, Kyoto, 603-8377, Japón",
        google_maps_place_id: "ChIJl2JyBiCoAWARaV4-RLkUeGM",
        rating: 4.8,
        specialty: "Matcha Tradicional & Repostería Japonesa",
        image: "images/restaurantes/sabo-kinkakuan-kyoto.jpg",
        nearTo: ["Kinkaku-ji", "Templo del Pabellón Dorado", "Pabellón Dorado", "Ryoan-ji", "Opción Tarde: El Pabellón Dorado", "Ninna-ji", "Santuario Kitano Tenmangu", "Funaoka Onsen"]
    },
    // --- RESTAURANTES DE TOKIO ---
    {
        id: "hikiniku-to-come-tokyo",
        name: "Hikiniku To come",
        category: "Hamburguesas de Wagyu (Parrilla)",
        description: "Increíble experiencia donde preparan hamburguesas de carne Wagyu a la plancha de carbón directamente frente a ti. Muy popular, id a por la mañana a coger ticket o reservad con tiempo.",
        area: "Shibuya, Tokio",
        city: "TOKYO",
        address: "Dogenzaka, Shibuya, Tokyo",
        google_maps_place_id: "ChIJsWJ80PiNGGAR8aSF8OFJeu4",
        rating: 4.4,
        specialty: "Hamburguesas Wagyu al Carbón", 
        image: "images/restaurantes/hikiniku-to-come-tokyo.jpg",
        nearTo: ["Shibuya", "Harajuku", "Omotesando", "Shibuya Crossing", "Shibuya Sky", "Avenida Omotesando", "Santuario Meiji", "Modo Karaoke"]
    },
    {
        id: "kanimamire-ikebukuro",
        name: "Kanimamire Tokyo Ikebukuro",
        category: "Buffet libre de Cangrejo",
        description: "El paraíso para los amantes del marisco. Ofrecen un buffet libre de espectacular cangrejo nevado gigante, patas de rey y mucho más. Una comilona épica.",
        area: "Ikebukuro, Tokio",
        city: "TOKYO",
        address: "Ikebukuro, Toshima City, Tokyo",
        google_maps_place_id: "ChIJY0rMjjGNGGARbAkNUEitbog",
        rating: 4.8,
        specialty: "Buffet de Cangrejo Real y Nevado", 
        image: "images/restaurantes/kanimamire-ikebukuro.jpg",
        nearTo: ["Ikebukuro", "Sunshine City"]
    },
    {
        id: "ramen-nagi-shinjuku",
        name: "Ramen Nagi",
        category: "Ramen de Anchoas (Niboshi)",
        description: "Una pequeña joya oculta de ramen en el bullicio de Shinjuku. Famoso por su potentísimo y súper umami caldo Niboshi (hecho de abundantes anchoas secas).",
        area: "Shinjuku, Tokio",
        city: "TOKYO",
        address: "Kabukicho, Shinjuku, Tokyo",
        google_maps_place_id: "ChIJAxKeZNmMGGARQ4EOGHqSdIg",
        rating: 4.3,
        specialty: "Ramen Niboshi (Caldo de Anchoas Secas)", 
        image: "images/restaurantes/ramen-nagi-shinjuku.jpg",
        nearTo: ["Shinjuku", "Kabukicho", "Golden Gai", "Gobierno Metropolitano", "Omoide Yokocho", "Godzilla", "Tren a Shinjuku", "Llegada a Shinjuku", "Samurai Restaurant Show", "Shinjuku Gyoen"]
    },
    {
        id: "yakiniku-washino-shinjuku",
        name: "Yakiniku Washino Shinjuku",
        category: "Yakiniku (Barbacoa Wagyu)",
        description: "Opción premium de Yakiniku en Shinjuku. Si queréis daros un homenaje de carne Wagyu A5 que se deshace en la boca, con cortes espectaculares y gran ambiente.",
        area: "Shinjuku, Tokio",
        city: "TOKYO",
        address: "Shinjuku, Tokyo",
        google_maps_place_id: "ChIJO8w-gdyMGGAR-4Chzri55f8",
        rating: 4.9,
        specialty: "Cortes Finos de Wagyu A5 al Carbón", 
        image: "images/restaurantes/yakiniku-washino-shinjuku.jpg",
        nearTo: ["Shinjuku", "Kabukicho", "Godzilla", "Omoide Yokocho", "Shinjuku San-chome", "Samurai Restaurant Show", "Shinjuku Gyoen"]
    },
    {
        id: "pizza-marumo-tokyo",
        name: "Pizza Marumo",
        category: "Pizza Napolitana Premium",
        description: "Un respiro occidental excelente. Famosos por conseguir unas masas de pizza napolitana increíbles (toda una religión en Japón) en un ambiente moderno y de diseño.",
        area: "Ebisu, Tokio",
        city: "TOKYO",
        address: "Ebisu, Shibuya City, Tokyo",
        google_maps_place_id: "ChIJq6aDrAiLGGAR_99_HFsCvqk",
        rating: 4.4,
        specialty: "Pizza de Trufa y Champiñones", 
        image: "images/restaurantes/pizza-marumo-tokyo.jpg",
        nearTo: ["Ebisu", "Shibuya", "Daikanyama", "Roppongi", "Roppongi Hills"]
    },
    {
        id: "wagyu-burger-hirokiya",
        name: "Wagyu Burger Hirokiya",
        category: "Hamburguesas Extremas (Wagyu)",
        description: "Se hizo muy viral por aplastar físicamente (smash) bolas de carne de Wagyu en la plancha, resultando en unas burgers increíblemente grasas y sabrosas.",
        area: "Ebisu / Shibuya, Tokio",
        city: "TOKYO",
        address: "Ebisu, Shibuya City, Tokyo",
        google_maps_place_id: "ChIJVy_krISLGGARQPa7gFKXErM",
        rating: 4.8,
        specialty: "Wagyu Smash Burger", 
        image: "images/restaurantes/wagyu-burger-hirokiya.jpg",
        nearTo: ["Ebisu", "Shibuya", "Daikanyama", "Roppongi", "Roppongi Hills"]
    },
    {
        id: "yakiniku-kappo-note",
        name: "Yakiniku Kappo Note",
        category: "Yakiniku Elegante (Kappo)",
        description: "Para una experiencia más enfocada en la atención detallada (Kappo). La carne es seleccionada y asada con precisión milimétrica en un ambiente inmejorable.",
        area: "Ginza, Tokio",
        city: "TOKYO",
        address: "Ginza, Chuo City, Tokyo",
        google_maps_place_id: "ChIJLaZ-H1CLGGARDWuOinQuVfE",
        rating: 4.8,
        specialty: "Menú Degustación Yakiniku Kappo", 
        image: "images/restaurantes/yakiniku-kappo-note.jpg",
        nearTo: ["Ginza", "Tsukiji", "Palacio Imperial", "Marunouchi", "Azabujuban", "Mercado Tsukiji", "Teatro Kabuki-za"]
    },
    {
        id: "rare-tendon-mitsuyoshi",
        name: "Rare Tendon Ginza Mitsuyoshi",
        category: "Rare Tendon (Tempura Poco Hecha)",
        description: "Su especialidad es un bol de arroz enorme cubierto de una montaña de ingredientes de primer nivel en una espectacular y crujiente floritura de tempura 'poco hecha'.",
        area: "Ginza, Tokio",
        city: "TOKYO",
        address: "Ginza, Chuo City, Tokyo",
        google_maps_place_id: "ChIJcWfg_KeLGGAR3oyNuKRGML4",
        rating: 4.4,
        specialty: "Tendon de Mariscos en Flor de Tempura", 
        image: "images/restaurantes/rare-tendon-mitsuyoshi.jpg",
        nearTo: ["Ginza", "Tsukiji", "Tsukiji Outer Market", "Mercado de Pescado", "Mercado Tsukiji", "Teatro Kabuki-za", "Yurakucho", "Estación de Tokio", "Toyosu Market", "Senkyaku Banrai"]
    },
    {
        id: "ginza-kagari-ramen",
        name: "Ginza Kagari",
        category: "Ramen Tori Paitan (Caldo de Pollo)",
        description: "Considerado uno de los mejores ramen de pollo de Tokio. Su caldo es tan cremoso, blanco y espeso que parece un potaje premium adornado de vegetales exquisitos.",
        area: "Ginza, Tokio",
        city: "TOKYO",
        address: "Ginza, Chuo City, Tokyo",
        google_maps_place_id: "ChIJjykJZCCLGGARMx5vYqRsWYI",
        rating: 4.2,
        specialty: "Tori Paitan Ramen (Crema de Pollo)", 
        image: "images/restaurantes/ginza-kagari-ramen.jpg",
        nearTo: ["Ginza", "Tsukiji", "Palacio Imperial", "Yurakucho", "Estación de Tokio", "Mercado Tsukiji", "Teatro Kabuki-za", "Marunouchi", "Toyosu Market", "Senkyaku Banrai"]
    },
    {
        id: "ginza-cafe-hanon",
        name: "Ginza Cafe Hanon",
        category: "Café & Pankakes",
        description: "Sus fluffy pancakes (tortitas suflé híper esponjosas que tiemblan al mover el plato) atraen a todo el mundo a Ginza. Genial para matar el gusanillo dulce al mediodía.",
        area: "Ginza, Tokio",
        city: "TOKYO",
        address: "Ginza, Chuo City, Tokyo",
        google_maps_place_id: "ChIJR1xFwwGLGGARuV2Z-PGta4k",
        rating: 4.2,
        specialty: "Fluffy Pancakes (Tortitas Esponjosas)", 
        image: "images/restaurantes/ginza-cafe-hanon.jpg",
        nearTo: ["Ginza", "Tsukiji", "Marunouchi", "Estación de Tokio", "Mercado Tsukiji", "Teatro Kabuki-za", "Yurakucho", "Toyosu Market", "Senkyaku Banrai"]
    },
    {
        id: "400c-pizza-tokyo",
        name: "400℃ PIZZA TOKYO",
        category: "Pizza Napolitana Premium",
        description: "Famosa pizzería que sirve una de las mejores pizzas de estilo napolitano de Tokio, conocida por su masa ligera cocinada a altísima temperatura (400℃).",
        area: "Kagurazaka, Tokio",
        city: "TOKYO",
        address: "kif annex, 102 13-1 Wakamiyacho, Shinjuku City, Tokyo 162-0827, Japón",
        google_maps_place_id: "ChIJL5ghJACNGGARayhWqa62-8E",
        rating: 4.2,
        specialty: "Pizza Margherita Napolitana Premium",
        image: "images/restaurantes/400c-pizza-tokyo.jpg",
        nearTo: ["Kagurazaka", "Iidabashi", "Hotel Edmont", "Check-in Edmont", "Jardín Koishikawa Korakuen", "Shinjuku", "Kabukicho"]
    },
    {
        id: "meat-eat-up-kichijoji",
        name: "Meat Eat UP ステーキハウス 吉祥寺",
        category: "Steakhouse / Barbacoa",
        description: "Acogedor restaurante de carnes especializado en chuletones y cortes de ternera premium cocinados al punto exacto, ubicado en Kichijoji.",
        area: "Kichijoji, Musashino",
        city: "TOKYO",
        address: "Japón, 〒180-0004 Tokyo, Musashino, Kichijoji Honcho, 1 Chome−23−7 沢村ビル B1F",
        google_maps_place_id: "ChIJ9_DkQMrvGGAR4OClW3SkrmU",
        rating: 4.3,
        specialty: "Ribeye Steak a la Parrilla",
        image: "images/restaurantes/meat-eat-up-kichijoji.jpg",
        nearTo: ["Parque Inokashira", "Shibuya", "Kichijoji", "Mitaka", "Museo Ghibli", "Nakano", "Nakano Broadway"]
    },
    {
        id: "pizza-strada-tokyo",
        name: "Pizza Strada",
        category: "Pizza Napolitana Premium",
        description: "Galardonada pizzería de estilo napolitano con horno de leña, famosa por su masa fina e ingredientes frescos de gran calidad. Un imprescindible en Azabujuban.",
        area: "Azabujuban, Tokio",
        city: "TOKYO",
        address: "Japón, 〒106-0045 Tokyo, Minato City, Azabujuban, 3 Chome−6−2 １F NS",
        google_maps_place_id: "ChIJc5qDraGLGGARUjC1cEGOBac",
        rating: 4.4,
        specialty: "Pizza Strada (Jamón, Rúcula y Huevo)",
        image: "images/restaurantes/pizza-strada-tokyo.jpg",
        nearTo: ["Azabujuban", "Roppongi", "Torre de Tokio", "Roppongi Hills", "TeamLab Borderless", "Azabudai Hills"]
    },
    {
        id: "shogun-pizza-shibuya",
        name: "SHOGUN PIZZA 渋谷店",
        category: "Pizza Artesanal",
        description: "Pizzería moderna ubicada en Shibuya, que destaca por sus masas crujientes e ingredientes innovadores, incluyendo carne de Wagyu.",
        area: "Shibuya, Tokio",
        city: "TOKYO",
        address: "Japón, 〒150-0042 Tokyo, Shibuya, Udagawacho, 13−4 Spain坂OKビル １F",
        google_maps_place_id: "ChIJPRBzpJuNGGARQpQ1b4VVR6w",
        rating: 4.7,
        specialty: "Pizza de Wagyu y Setas Shiitake",
        image: "images/restaurantes/shogun-pizza-shibuya.jpg",
        nearTo: ["Shibuya Crossing", "Harajuku", "Shibuya", "Spain-zaka", "Takeshita Street", "Shibuya Sky"]
    },
    {
        id: "wagyu-brothers-asakusa",
        name: "THE WAGYU BROTHERS",
        category: "Hamburguesas & Carne Wagyu",
        description: "Excelente local especializado en jugosas y espectaculares hamburguesas y bocadillos de carne Wagyu A5 de primera calidad en Asakusa.",
        area: "Asakusa, Tokio",
        city: "TOKYO",
        address: "Japón, 〒111-0032 Tokyo, Taito City, Asakusa, 1 Chome−18−3 遠藤ビル 2F",
        google_maps_place_id: "ChIJkeeXWiOPGGARdyq-rIwctCo",
        rating: 4.9,
        specialty: "Wagyu Cheeseburger con Patatas",
        image: "images/restaurantes/wagyu-brothers-asakusa.jpg",
        nearTo: ["Senso-ji", "Akihabara", "Asakusa", "Nakamise", "Calle Nakamise", "Río Sumida", "Tokyo Skytree", "Skytree", "Calle Kappabashi", "Crucero Fluvial Hotaluna", "Experiencia Maid Café", "Últimas compras por Tokio"]
    },
    {
        id: "forno-nishiazabu",
        name: "FORNO Nishiazabu",
        category: "Steakhouse / Carne Wagyu",
        description: "Exclusivo y elegante restaurante especializado en cortes de carne Wagyu premium cocinados a la parrilla de carbón en un ambiente íntimo y sofisticado.",
        area: "Nishiazabu, Tokio",
        city: "TOKYO",
        address: "Japón, 〒106-0031 Tokyo, Minato City, Nishiazabu, 4 Chome−11−25 Modern Form Nishiazabu Building 3F Part III",
        google_maps_place_id: "ChIJBRT31B-LGGARo5Z6uvdAJLI",
        rating: 4.5,
        specialty: "Chuletón Wagyu Asado al Carbón",
        image: "images/restaurantes/forno-nishiazabu.jpg",
        nearTo: ["Nishiazabu", "Roppongi", "Roppongi Hills", "Shibuya"]
    },
    {
        id: "kikanbo-ramen-tokyo",
        name: "Kikanbo Ramen (鬼金棒)",
        category: "Ramen Picante (Karashige Miso)",
        description: "Famoso por su espectacular miso ramen picante donde puedes personalizar el nivel de picante (Kara) y de pimienta de Sichuan (Shige) que adormece la boca.",
        area: "Kanda, Tokio",
        city: "TOKYO",
        address: "2 Chome-10-9 Kajicho, Chiyoda City, Tokyo 101-0044, Japón",
        google_maps_place_id: "ChIJ0ZJ-DwKMGGARDfmgrVH1HLY",
        rating: 4.4,
        specialty: "Karashige Miso Ramen (Picante & Sichuan)",
        image: "images/restaurantes/kikanbo-ramen-tokyo.jpg",
        nearTo: ["Akihabara", "Estación de Tokio", "Kanda", "Kanda Myōjin", "Experiencia Maid Café", "Parque Ueno", "Mercado Ameyoko", "Ameyoko", "Últimas compras por Tokio"]
    },
    {
        id: "age3-harajuku",
        name: "Age.3×Q HARAJUKU",
        category: "Sándwiches Fritos & Nata",
        description: "Sensación viral en Harajuku que sirve pan frito súper crujiente relleno de abundante nata montada fresca y coberturas dulces o saladas de todo tipo.",
        area: "Harajuku, Tokio",
        city: "TOKYO",
        address: "Japón, 〒150-0001 Tokyo, Shibuya, Jingumae, 2 Chome-27-10 Q-ROOMS 1F",
        google_maps_place_id: "ChIJZzNC9sGNGGARV86Hj9kG57o",
        rating: 4.8,
        specialty: "Age-pan (Sándwich Frito de Nata Fresca)",
        image: "images/restaurantes/age3-harajuku.jpg",
        nearTo: ["Harajuku", "Takeshita Street", "Omotesando", "Harajuku (Takeshita Street)", "Avenida Omotesando", "Santuario Meiji", "Shibuya"]
    },
    {
        id: "dolce-tacubo-tokyo",
        name: "DOLCE TACUBO",
        category: "Repostería Gourmet / Postres",
        description: "Exquisito local de postres para llevar creado por el chef con estrella Michelin de TACUBO, famoso por sus financiers recién horneados y sus espectaculares choux à la crème.",
        area: "Daikanyama, Tokio",
        city: "TOKYO",
        address: "Japón, 〒150-0021 Tokyo, Shibuya, Ebisunishi, 2 Chome-15-9  チェラーザ代官山 1F",
        google_maps_place_id: "ChIJvaN4mliLGGAR6t4CkHY0hCw",
        rating: 4.2,
        specialty: "Choux à la Crème recién horneado",
        image: "images/restaurantes/dolce-tacubo-tokyo.jpg",
        nearTo: ["Shibuya", "Ebisu", "Daikanyama"]
    },
    {
        id: "gyukatsu-motomura-shibuya",
        name: "Gyukatsu Motomura (Shibuya)",
        category: "Gyukatsu (Ternera empanada)",
        description: "Famoso por su filete de ternera empanado (Gyukatsu) súper tierno y jugoso, servido poco hecho para que lo termines de cocinar a tu gusto en tu propia plancha caliente de piedra.",
        area: "Shibuya, Tokio",
        city: "TOKYO",
        address: "Japón, 〒150-0002 Tokyo, Shibuya, 3 Chome−18−10 2F",
        google_maps_place_id: "ChIJn2FoeFmLGGARnIog2ijRZXw",
        rating: 4.9,
        specialty: "Gyukatsu (Ternera Empanada a la Piedra)",
        image: "images/restaurantes/gyukatsu-motomura-shibuya.jpg",
        nearTo: ["Shibuya Crossing", "Shibuya Sky", "Harajuku", "Shibuya", "Modo Karaoke"]
    },
    {
        id: "hikiniku-to-kome-kichijoji",
        name: "Hikiniku To Kome (Kichijoji)",
        category: "Hamburguesas de Wagyu (Parrilla)",
        description: "El local original de este famosísimo concepto donde comes jugosas hamburguesas de ternera Wagyu recién hechas al carbón acompañadas de arroz ilimitado y un huevo crudo.",
        area: "Kichijoji, Musashino",
        city: "TOKYO",
        address: "Japón, 〒180-0004 Tokyo, Musashino, Kichijoji Honcho, 2 Chome-8-3 1F",
        google_maps_place_id: "ChIJqdnczB3vGGARH6a7Qauu5CY",
        rating: 4.4,
        specialty: "Hamburguesas de Wagyu con Huevo Crudo",
        image: "images/restaurantes/hikiniku-to-kome-kichijoji.jpg",
        nearTo: ["Parque Inokashira", "Mitaka", "Kichijoji", "Museo Ghibli", "Nakano", "Nakano Broadway"]
    },
    {
        id: "nihon-miyabi-asakusa",
        name: "Nihon Miyabi Asakusa Main Store",
        category: "Artesanías & Souvenirs Japoneses",
        description: "Boutique encantadora de souvenirs y artesanías japonesas ubicada en un histórico edificio mercantil centenario en Asakusa. Ideal para comprar cerámica, vajilla, abanicos y detalles artesanales únicos.",
        area: "Asakusa, Tokio",
        city: "TOKYO",
        address: "Japón, 〒111-0032 Tokyo, Taito City, Asakusa, 1 Chome−11−1  ザ・浅草レジデンス 103",
        google_maps_place_id: "ChIJ8zHFBg2PGGARb5lknI7tlSo",
        rating: 5,
        specialty: "Vajillas Edo-kiriko y Abanicos Artesanales",
        image: "images/restaurantes/nihon-miyabi-asakusa.jpg",
        nearTo: ["Senso-ji", "Calle Nakamise", "Asakusa", "Nakamise", "Calle Kappabashi"]
    },
    {
        id: "sukemasa-coffee-tokyo",
        name: "Sukemasa Coffee (スケマサ コーヒー)",
        category: "Café & Repostería",
        description: "Famosa cafetería en Asakusa servida por baristas vestidos con kimono tradicional, conocida por su café de especialidad, sus espectaculares sándwiches de fruta fresca (Fruit Sando) y repostería artesanal.",
        area: "Asakusa, Tokio",
        city: "TOKYO",
        address: "Japón, 〒111-0032 Tokyo, Taito City, Asakusa, 2-chōme−29−２ 君塚ビル 102",
        google_maps_place_id: "ChIJx0YfggGPGGARxC5wrIo3Gxk",
        rating: 4.4,
        specialty: "Fruit Sando & Café de Especialidad",
        image: "images/restaurantes/sukemasa-coffee-tokyo.jpg",
        nearTo: ["Senso-ji", "Asakusa", "Calle Nakamise", "Nakamise", "Calle Kappabashi", "Crucero Fluvial Hotaluna"]
    },
    {
        id: "tonkatsu-maisen-aoyama",
        name: "Tonkatsu Maisen Aoyama",
        category: "Tonkatsu (Cerdo Empanado)",
        description: "El templo definitivo del Tonkatsu en Tokio, ubicado en una antigua casa de baños pública convertida en restaurante. Su solomillo de cerdo Kurobuta empanado es tan increíblemente tierno que se puede cortar con los palillos.",
        area: "Aoyama / Omotesando, Tokio",
        city: "TOKYO",
        address: "4-chōme-8-5 Jingūmae, Shibuya, Tokyo 150-0001, Japan",
        google_maps_place_id: "ChIJa2mnui2NGGAR7z4tvWkl7HM",
        rating: 4.4,
        specialty: "Tonkatsu Kurobuta (Solomillo de Cerdo)",
        image: "images/restaurantes/tonkatsu-maisen-aoyama.jpg",
        nearTo: ["Omotesando", "Harajuku", "Shibuya", "Avenida Omotesando", "Aoyama", "Santuario Meiji"]
    },
    {
        id: "crayon-shinchan-shop-tokyo",
        name: "Crayon Shin-chan Official Shop",
        category: "Tienda Oficial & Merchandising",
        description: "La tienda oficial (Action Department Store) dedicada al icónico personaje de anime Shin-chan en Tokyo Character Street. Ideal para conseguir peluches exclusivos, figuras, souvenirs divertidos y productos artesanales.",
        area: "Estación de Tokio (Tokyo Character Street), Tokio",
        city: "TOKYO",
        address: "Japón, 〒100-0005 Tokyo, Chiyoda City, Marunouchi, 1-chōme−9−１ Tokyo Character Street (Estación de Tokio)",
        google_maps_place_id: "ChIJGeYlX_mLGGAR6zAbbFYf_7Q",
        rating: 4.4,
        specialty: "Merchandising Exclusivo de Shin-chan",
        image: "images/restaurantes/crayon-shinchan-shop-tokyo.jpg",
        nearTo: ["Estación de Tokio", "Tokyo Character Street", "Marunouchi", "Nihonbashi", "Ginza", "Ginza Luxury"]
    }
];

// Exportación global
window.restaurantData = restaurantData;
