const CACHE_NAME = 'japon-2026-v4';

// Esta lista será reemplazada automáticamente por el script de Python.
const ASSETS_TO_CACHE = [
  
    "./",
    "./index.html",
    "https://unpkg.com/leaflet@1.9.4/dist/leaflet.css",
    "https://unpkg.com/leaflet@1.9.4/dist/leaflet.js",
    "https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;600;800&display=swap",
    "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css",
    "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2",
    "data.js",
    "data_combinator.js",
    "data_dias_00_08.js",
    "data_dias_09_16.js",
    "data_dias_17_24.js",
    "data_restaurants.js",
    "generar_guia.html",
    "index.html",
    "manifest.json",
    "persistence.js",
    "script.js",
    "script_engine.js",
    "script_tactical.js",
    "style.css",
    "images/adashino-nembutsuji.jpg",
    "images/add-anamori.jpg",
    "images/add-bear-park.jpg",
    "images/add-daikakuji.jpg",
    "images/add-engakuji.jpg",
    "images/add-fuji-caves.jpg",
    "images/add-fujinomiya.jpg",
    "images/add-funaoka.jpg",
    "images/add-fushimi-sake.jpg",
    "images/add-gion-shirakawa.jpg",
    "images/add-heian.jpg",
    "images/add-hida-no-sato.jpg",
    "images/add-hirayu-waterfall.jpg",
    "images/add-hotaluna.jpg",
    "images/add-hozugawa.jpg",
    "images/add-isuien.jpg",
    "images/add-jonanjima.jpg",
    "images/add-kaiyukan.jpg",
    "images/add-kamogawa.jpg",
    "images/add-kanda-myojin.jpg",
    "images/add-kawagoe.jpg",
    "images/add-kenninji.jpg",
    "images/add-kimono.jpg",
    "images/add-kitano.jpg",
    "images/add-koishikawa.jpg",
    "images/add-matsuri-no-mori.jpg",
    "images/add-music-forest.jpg",
    "images/add-namba-yasaka.jpg",
    "images/add-nara-museum.jpg",
    "images/add-night-walk.jpg",
    "images/add-ninnaji.jpg",
    "images/add-nishi-honganji.jpg",
    "images/add-okawa-cruise.jpg",
    "images/add-osaka-history.jpg",
    "images/add-osaka-housing.jpg",
    "images/add-sakurayama.jpg",
    "images/add-samurai-museum.jpg",
    "images/add-sanjusangendo.jpg",
    "images/add-shinjuku-gyoen.jpg",
    "images/add-shinkyo.jpg",
    "images/add-sumida-aquarium.jpg",
    "images/add-sumiyoshi.jpg",
    "images/add-tofukuji.jpg",
    "images/add-tsuruhashi.jpg",
    "images/add-wakakusa.jpg",
    "images/aeropuerto_madrid.png",
    "images/akihabara.png",
    "images/arashiyama.png",
    "images/avion.jpg",
    "images/avion.png",
    "images/bahia osaka.png",
    "images/bon_dance.png",
    "images/casa.jpg",
    "images/castillo osaka.png",
    "images/castillo_osaka.png",
    "images/cena ligera.png",
    "images/cena_despedida.png",
    "images/check in.png",
    "images/chureito_pagoda.png",
    "images/den-den-town.jpg",
    "images/dia1-vuelo.jpg",
    "images/dia1-vuelo.png",
    "images/dia10-heian.jpg",
    "images/dia10-itinerario-base-1.jpg",
    "images/dia10-itinerario-base.jpg",
    "images/dia10-nishiki.jpg",
    "images/dia10-ohara.jpg",
    "images/dia10-portada.jpg",
    "images/dia11-itinerario-base-1.jpg",
    "images/dia11-itinerario-base.jpg",
    "images/dia11-shinhotaka.jpg",
    "images/dia11-teleferico.jpg",
    "images/dia11-zen.jpg",
    "images/dia12-higashiyama.jpg",
    "images/dia12-itinerario-base.jpg",
    "images/dia12-jinya.jpg",
    "images/dia12-yatai-kaikan.jpg",
    "images/dia12-yatai.jpg",
    "images/dia13-chureito.jpg",
    "images/dia13-oshino.jpg",
    "images/dia13-portada.jpg",
    "images/dia13-saiko.jpg",
    "images/dia14-5-estacion-fuji.jpg",
    "images/dia14-honcho.jpg",
    "images/dia14-itinerario-base.jpg",
    "images/dia14-sengen.jpg",
    "images/dia14-shiraito.jpg",
    "images/dia15-fuji.jpg",
    "images/dia15-honcho-street.jpg",
    "images/dia15-itinerario-base.jpg",
    "images/dia15-iyashi.jpg",
    "images/dia15-portada.jpg",
    "images/dia15-ryugatake.jpg",
    "images/dia16-coche.jpg",
    "images/dia16-kagurazaka.jpg",
    "images/dia17-asakusa.jpg",
    "images/dia17-bandai.jpg",
    "images/dia17-calle-kappabashi-cocineros.jpg",
    "images/dia17-hoppy.jpg",
    "images/dia17-kappabashi.jpg",
    "images/dia17-sensoji.jpg",
    "images/dia17-skytree.jpg",
    "images/dia17-sumida.jpg",
    "images/dia17-ueno.jpg",
    "images/dia18-harajuku.jpg",
    "images/dia18-kabukicho.jpg",
    "images/dia18-meiji.jpg",
    "images/dia18-omotesando.jpg",
    "images/dia18-shibuya.jpg",
    "images/dia18-shinjuku-gyoen.jpg",
    "images/dia18-sky.jpg",
    "images/dia18-tocho.jpg",
    "images/dia19-akihabara.jpg",
    "images/dia19-ginza.jpg",
    "images/dia19-harrypotter.jpg",
    "images/dia19-maid.jpg",
    "images/dia19-palacio.jpg",
    "images/dia19-tokyo-station.jpg",
    "images/dia19-tsukiji.jpg",
    "images/dia2-osaka.jpg",
    "images/dia20-disneysea.jpg",
    "images/dia20-itinerario-base-1.jpg",
    "images/dia20-itinerario-base-2.jpg",
    "images/dia20-itinerario-base.jpg",
    "images/dia20-joypolis.jpg",
    "images/dia20-monorail.jpg",
    "images/dia20-museo-nacional-tokio.jpg",
    "images/dia20-odaiba-compras.jpg",
    "images/dia20-odaiba.jpg",
    "images/dia20-spa.jpg",
    "images/dia20-teamlab.jpg",
    "images/dia20-toyosu.jpg",
    "images/dia21-ghibli.jpg",
    "images/dia21-ikebukuro.jpg",
    "images/dia21-kegon.jpg",
    "images/dia21-nakano.jpg",
    "images/dia21-nikko.jpg",
    "images/dia21-shimokitazawa.jpg",
    "images/dia21-tokyo-dome.jpg",
    "images/dia22-donki.jpg",
    "images/dia22-enoshima.jpg",
    "images/dia22-itinerario-base.jpg",
    "images/dia22-kamakura.jpg",
    "images/dia22-maletas.jpg",
    "images/dia22-roppongi.jpg",
    "images/dia22-teatro-kabuki-za.jpg",
    "images/dia22-toyosu.jpg",
    "images/dia22-yokohama.jpg",
    "images/dia23-itinerario-base-1.jpg",
    "images/dia23-itinerario-base.jpg",
    "images/dia23-portada.jpg",
    "images/dia23-terminal-3-haneda.jpg",
    "images/dia24-home.jpg",
    "images/dia3-abeno.jpg",
    "images/dia3-acuario.jpg",
    "images/dia3-acuario.png",
    "images/dia3-castillo.jpg",
    "images/dia3-castillo.png",
    "images/dia3-itinerario-base.jpg",
    "images/dia3-portada.jpg",
    "images/dia3-shinsekai.jpg",
    "images/dia3-umeda.jpg",
    "images/dia3-umeda.png",
    "images/dia4-buda.jpg",
    "images/dia4-buda.png",
    "images/dia4-ciervos.jpg",
    "images/dia4-kobe.jpg",
    "images/dia4-minoh.jpg",
    "images/dia4-nara.jpg",
    "images/dia4-portada.jpg",
    "images/dia4-portada.png",
    "images/dia5-kuromon.jpg",
    "images/dia5-miyajima.jpg",
    "images/dia5-portada.jpg",
    "images/dia5-usj.jpg",
    "images/dia6-despliegue-capital-imperial.jpg",
    "images/dia6-fushimi.jpg",
    "images/dia6-kyoto-tower.jpg",
    "images/dia6-portada.jpg",
    "images/dia6-toji.jpg",
    "images/dia7-ginkakuji.jpg",
    "images/dia7-gion.png",
    "images/dia7-historico.jpg",
    "images/dia7-kiyomizu.jpg",
    "images/dia7-nijo.jpg",
    "images/dia7-pontocho.jpg",
    "images/dia7-portada.jpg",
    "images/dia7-yasaka.jpg",
    "images/dia8-bambu.jpg",
    "images/dia8-itinerario-base-1.jpg",
    "images/dia8-itinerario-base-2.jpg",
    "images/dia8-itinerario-base.jpg",
    "images/dia8-monos.png",
    "images/dia8-puente.png",
    "images/dia8-sagano.jpg",
    "images/dia8-toei.jpg",
    "images/dia9-himeji.jpg",
    "images/dia9-kurama.jpg",
    "images/dia9-uji.jpg",
    "images/disneysea.png",
    "images/doguyasuji.jpg",
    "images/dotonbori.png",
    "images/ebisubashi-suji.jpg",
    "images/estambul.png",
    "images/filosofo.png",
    "images/fuji_climb.png",
    "images/fuji_lago.png",
    "images/fuji_ropeway.png",
    "images/fuji_sanctuary.png",
    "images/fuji_summit.png",
    "images/fushimi_inari.png",
    "images/ginkakuji.png",
    "images/ginza.png",
    "images/gion.png",
    "images/hama_rikyu.png",
    "images/haneda.png",
    "images/heian_shrine.png",
    "images/higashiyama_walk.png",
    "images/honcho_street.png",
    "images/hotel-dc-sakura.jpg",
    "images/hotel-haostay.jpg",
    "images/hotel-kazeya.jpg",
    "images/hotel-kyoto-tower.jpg",
    "images/hotel-metropolitan-tokio.jpg",
    "images/hotel-residence-takayama.jpg",
    "images/hotel-sotetsu-tokyo.jpg",
    "images/hotel-toyoko-kawaguchiko.jpg",
    "images/hotel-wing-osaka.jpg",
    "images/hotel_osaka.jpg",
    "images/hotel_osaka.png",
    "images/isshinji-temple.jpg",
    "images/iyashi_sato.png",
    "images/izakaya.png",
    "images/kamakura_buda.png",
    "images/kawaramachi.jpg",
    "images/kinkakuji.png",
    "images/kiyomizudera.png",
    "images/kurama_kibune.png",
    "images/kyoto_tower.png",
    "images/limusine.png",
    "images/meiji_jingu.png",
    "images/mitsutoge.png",
    "images/miyajima.png",
    "images/mundo.png",
    "images/nakano_broadway.png",
    "images/namba-parks.jpg",
    "images/nijo_castle.png",
    "images/nishiki_market.png",
    "images/odaiba.png",
    "images/ohara_moss.png",
    "images/oishi_park_atardecer.jpg",
    "images/okuhida_ryokan.png",
    "images/onsen_fuji.png",
    "images/oshino_hakkai.png",
    "images/otagi-nembutsuji.jpg",
    "images/palacio-imperial-kyoto.jpg",
    "images/paseo-filosofo.jpg",
    "images/peninsula.png",
    "images/ramen.png",
    "images/roppongi_hills.png",
    "images/ryugatake.png",
    "images/sagano_train.png",
    "images/saiko_lake.png",
    "images/sengen_jinja.png",
    "images/sensoji.png",
    "images/shibuya_crossing.png",
    "images/shibuya_sky.png",
    "images/shinhotaka_onsen.png",
    "images/shinhotaka_ropeway.png",
    "images/shinjuku.png",
    "images/shinsaibashi-parco.jpg",
    "images/shinsaibashi.png",
    "images/shiraito_waterfall.png",
    "images/shoji_lake.png",
    "images/skytree.png",
    "images/skytree_noche.png",
    "images/sushi.png",
    "images/takayama.png",
    "images/takayama_jinya.png",
    "images/teamlab.png",
    "images/teamlab_lanterns.png",
    "images/toei_studio.png",
    "images/tokio_skyline.png",
    "images/tokyo_midtown.png",
    "images/uji_tea.png",
    "images/umeda.png",
    "images/universal.png",
    "images/valencia.png",
    "images/yatai_kaikan.png",
    "images/restaurantes/chao-chao-gyoza-kiyamachi.jpg",
    "images/restaurantes/ginza-cafe-hanon.jpg",
    "images/restaurantes/ginza-kagari-ramen.jpg",
    "images/restaurantes/gyukatsu-motomura-kyoto.jpg",
    "images/restaurantes/hikiniku-to-come-tokyo.jpg",
    "images/restaurantes/kanimamire-ikebukuro.jpg",
    "images/restaurantes/kitan-hibiki-yakiniku.jpg",
    "images/restaurantes/matsusakagyu-yakiniku-m-namba.jpg",
    "images/restaurantes/my-neighbor.jpg",
    "images/restaurantes/nikugoro-amerikamura.jpg",
    "images/restaurantes/pizza-marumo-tokyo.jpg",
    "images/restaurantes/ramen-nagi-shinjuku.jpg",
    "images/restaurantes/rare-tendon-mitsuyoshi.jpg",
    "images/restaurantes/tempura-no-mise-gen.jpg",
    "images/restaurantes/unagi-sumito.jpg",
    "images/restaurantes/wagyu-burger-hirokiya.jpg",
    "images/restaurantes/yakiniku-kappo-note.jpg",
    "images/restaurantes/yakiniku-kitan-minamisenba.jpg",
    "images/restaurantes/yakiniku-m-hozenji.jpg",
    "images/restaurantes/yakiniku-washino-shinjuku.jpg",
    "infograf\u00eda/inf alpes.png",
    "infograf\u00eda/inf dia 0 1.png",
    "infograf\u00eda/inf dia 0.png",
    "infograf\u00eda/inf dia 1.png",
    "infograf\u00eda/inf dia 10.png",
    "infograf\u00eda/inf dia 11.png",
    "infograf\u00eda/inf dia 12.png",
    "infograf\u00eda/inf dia 14.png",
    "infograf\u00eda/inf dia 15.png",
    "infograf\u00eda/inf dia 16.png",
    "infograf\u00eda/inf dia 17.png",
    "infograf\u00eda/inf dia 18.png",
    "infograf\u00eda/inf dia 19.png",
    "infograf\u00eda/inf dia 3 1.png",
    "infograf\u00eda/inf dia 3.png",
    "infograf\u00eda/inf dia 4 1.png",
    "infograf\u00eda/inf dia 4.png",
    "infograf\u00eda/inf dia 5.png",
    "infograf\u00eda/inf dia 6.png",
    "infograf\u00eda/inf dia 7.png",
    "infograf\u00eda/inf dia 8.png",
    "infograf\u00eda/inf dia 9.png",
    "infograf\u00eda/inf kyoto.png",
    "infograf\u00eda/inf osaka.png",
    "infograf\u00eda/inf TOKIO.png",
    "infograf\u00eda/inf.png",
    "video/videoplayback.mp4"

];

self.addEventListener('install', event => {
    // skipWaiting fuerza la activación inmediata del nuevo service worker
    self.skipWaiting();
    event.waitUntil(
        caches.open(CACHE_NAME)
        .then(cache => {
            console.log('[Service Worker] Guardando archivos en caché...');
            return cache.addAll(ASSETS_TO_CACHE);
        })
        .catch(err => {
            console.error('[Service Worker] Error al cachear: ', err);
        })
    );
});

self.addEventListener('activate', event => {
    // Al activarse el nuevo service worker, borramos las cachés antiguas
    event.waitUntil(
        caches.keys().then(cacheNames => {
            return Promise.all(
                cacheNames.map(cacheName => {
                    if (cacheName !== CACHE_NAME) {
                        console.log('[Service Worker] Borrando caché antigua:', cacheName);
                        return caches.delete(cacheName);
                    }
                })
            );
        }).then(() => self.clients.claim())
    );
});

self.addEventListener('fetch', event => {
    // Estrategia: Cache First (Priorizar caché) para funcionar offline
    event.respondWith(
        caches.match(event.request)
        .then(response => {
            // Devuelve el archivo si está en la caché
            if (response) {
                return response;
            }
            
            // Si no está, hace la petición a la red original
            // Y de paso, clonamos la respuesta y la cacheamos dinámicamente
            return fetch(event.request).then(
                function(networkResponse) {
                    if(!networkResponse || networkResponse.status !== 200 || networkResponse.type !== 'basic') {
                        return networkResponse;
                    }

                    var responseToCache = networkResponse.clone();
                    caches.open(CACHE_NAME)
                        .then(function(cache) {
                            if (event.request.method === 'GET' && !event.request.url.startsWith('chrome-extension')) {
                                cache.put(event.request, responseToCache);
                            }
                        });

                    return networkResponse;
                }
            );
        }).catch(() => {
            // Manejo de errores offline puros
        })
    );
});
